title: CA Water Data Challenge
email: adborden@a14n.net
description: >-
  Map public water systems in California.
baseurl: "/ca-water-data-challenge" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: adborden
github_username:  adborden

# Build settings
source: src
markdown: kramdown
remote_theme: daviddarnes/alembic
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
